Repository brain-tec/odoonz-addons, pull requests merged in 2022-08, with the labels that each got.

#59 Syncing from upstream odoonz/odoonz-addons (15.0)
  auth_oauth_microsoft_graph/README.rst
Labels: 15.0

#60 Updating from latest 15.0
  auth_oauth_microsoft_graph/README.rst
Labels: 15.0.project_mi_465

#61 [t131097] Remove modules with installable=False
  account_anglosaxon_financial/__manifest__.py
  account_anglosaxon_financial/models/account_move.py
  account_anglosaxon_financial/wizards/account_move_reversal.py
  account_central_billing/__manifest__.py
  account_financial_risk_manager/__init__.py
  account_financial_risk_manager/__manifest__.py
  account_financial_risk_manager/security/ir.model.access.csv
  account_financial_risk_manager/views/res_partner_view.xml
  account_financial_risk_manager/wizards/__init__.py
  account_financial_risk_manager/wizards/partner_set_risk_wizard.py
  account_financial_risk_manager/wizards/partner_set_risk_wizard.xml
  account_invoice_cutoff_policy/__manifest__.py
  account_journal_lock_policy/__manifest__.py
  account_reconciliation_not_stupid/__manifest__.py
  account_supplier_tax_rounding/__manifest__.py
  documents_operating_unit/__manifest__.py
  invoice_sale_pricelist/__manifest__.py
  mail_no_subscribe_notify/__manifest__.py
  mc_operating_unit_fixes/__manifest__.py
  mc_operating_unit_fixes/models/account_move.py
  mc_operating_unit_fixes/security/portal.xml
  mrp_dynamic_line/__manifest__.py
  mrp_sale_fields/__manifest__.py
  partner_lock/__init__.py
  partner_lock/__manifest__.py
  partner_lock/models/__init__.py
  partner_lock/models/res_partner.py
  partner_lock/security/res_partner.xml
  partner_lock/views/res_partner.xml
  price_recalculation/__manifest__.py
  price_recalculation/wizards/price_recalculation.py
  product_attribute_group/__manifest__.py
  product_code_builder/__manifest__.py
  product_list_price_change/__manifest__.py
  product_no_translation/__manifest__.py
  product_supplierinfo_operating_unit/__manifest__.py
  product_variant_extra_price_options/__manifest__.py
  product_variant_extra_price_options/views/variant_templates.xml
  purchase_price_recalculation/__manifest__.py
  sale_financial_risk_enforce/__init__.py
  sale_financial_risk_enforce/__manifest__.py
  sale_financial_risk_enforce/models/__init__.py
  sale_financial_risk_enforce/models/res_company.py
  sale_financial_risk_enforce/models/res_config_settings.py
  sale_financial_risk_enforce/models/sale_order.py
  sale_financial_risk_enforce/views/res_config_settings.xml
  sale_price_recalculation/__manifest__.py
  sale_price_recalculation/wizards/sale_price_recalculation.py
  stock_account_operating_unit/__manifest__.py
  stock_filter_prodlot_qty/__manifest__.py
  stock_prodlot_qty/__manifest__.py
  stock_tracked_fifo_valuation/__manifest__.py
  stock_tracked_fifo_valuation/models/stock_move.py
  stock_warehouse_address/__manifest__.py
  tax_from_account/__manifest__.py
  tax_from_account/models/tax_from_account.py
  user_signature_logo/__manifest__.py
Labels: 15.0.project_mi_465

#62 Syncing from upstream odoonz/odoonz-addons (14.0)
  stock_prodlot_qty/views/stock_move.xml
Labels: 14.0
